### PR TITLE
Special Exams allowances

### LINKED ISSUE #88: Ticket - Allowances
# Designs
[Figma link](https://www.figma.com/design/RnkfsNvyutLkSDXEhEOkEY/Instructor-Experience?node-id=18416-127244&t=AIhzcasueWzcN3Go-11)

Image

**Add Allowance Modal**

Image

**Exam Types Dropdown**
[Figma link](https://www.figma.com/design/RnkfsNvyutLkSDXEhEOkEY/Instructor-Experience?node-id=18796-198427&t=AIhzcasueWzcN3Go-11)
Image

**Allowance Types**
[Figma link](https://www.figma.com/design/RnkfsNvyutLkSDXEhEOkEY/Instructor-Experience?node-id=18796-200148&t=AIhzcasueWzcN3Go-11)

Image

**Edit Allowance Modal**
[Figma link](https://www.figma.com/design/RnkfsNvyutLkSDXEhEOkEY/Instructor-Experience?node-id=19008-202692&t=AIhzcasueWzcN3Go-11)

Image

**Delete Allowance dialog**
Image

# Spec
- Data table shows a list of all allowances: one row per allowance
- If there are multiple allowances for a single user, they show up as separate rows
- Table has Username, Email, Exam Name, Allowance Type, Allowance Value, and actions column
- Actions are: Edit / Delete
    - [NEED TO CONFIRM WITH CURRENT IMPLEMENTATION] if a learner has taken the exam, using the allowance, the "Edit / Delete" options are inactive. upon hover, a tooltip displays the message "Cannot delete an allowance after learner has attempted the exam"
- Default sort is by username

**Add Allowance**
- User can specify multiple learners in the modal separated by commas
- Select Exam Type is a dropdown with Proctored and Timed
- All graded assignments in the course are listed  
- User can select many exams
- Allowance type: there are three
    - Additional Time
    - Review Policy Exception
    - Time Mulitiplier
- Depending on selected allowance type, the value changes:

Image

- upon creation, a new row is created for each unique learner and exam. For example, if two learners are selected, and two exams are selected, four row objects are created. 
- [TO CONFIRM] what happens if a second allowance is added with the same exam and user?

**Edit Allowance**
- Modal opens when user clicks "edit" from the kebab menu on a table row object
- Reuse the selected learner scope but remove ability to change selected learner
- User can edit exam type, allowance type, and value.
- User cannot edit the exam. Rows in the allowance table are one per user per exam. Modal is scoped in the same way (one user, one exam)
- The exam should have inactive styling

**Delete Allowance**
- User can select allowance and delete. Confirmation dialog displays as above.

### PR DESCRIPTION
**Pull request by diana-villalvazo-wgu**
## Description
As part of this PR we added all the functionality to Allowances Tab inside Special Exams Instructor Tab, you will be allowed to:
- See allowances table list
- Filter table by username or email
- Add new allowance
- Edit allowance
- Delete allowance

## Supporting information
Closes #88 

## Testing instructions
- Go to special exams tab
- Click on Allowances tab
- You should see the allowances table, add button, if you have allowances on the list you can see the actions 3 dot icon to display menu for edit or delete

## Other information
Screenshot 2026-04-26 at 12 42 59 p m

Screenshot 2026-04-26 at 12 47 11 p m

Screenshot 2026-04-26 at 12 46 57 p m

Screenshot 2026-04-26 at 12 43 29 p m

## LLM usage notice
Unit tests built with assistance from Claude.

## Best Practices Checklist

We're trying to move away from some deprecated patterns in this codebase. Please
check if your PR meets these recommendations before asking for a review:

- [x] Any _new_ files are using TypeScript (`.ts`, `.tsx`).
- [x] Deprecated `propTypes`, `defaultProps`, and `injectIntl` patterns are not used in any new or modified code.
- [x] Tests should use the helpers in `src/testUtils.tsx` (specifically `initializeMocks`)
- [x] Use React Query to load data from REST APIs. See any `apiHooks.ts` in this repo for examples.
- [x] All new i18n messages in `messages.ts` files have a `description` for translators to use.
- [x] Imports avoid using `../`. To import from parent folders, use `@src`, e.g. `import { initializeMocks } from '@src/testUtils';` instead of `from '../../../../testUtils'`

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @diana-villalvazo-wgu!


This repository is currently maintained by `@openedx/committers-frontend-app-instructor-dashboard`.


Once you've gone through the following steps feel free to tag them in a comment and let them know that your changes are ready for engineering review.

<details><summary>:radio_button: Get product approval</summary>

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.
</details>

<details><summary>:radio_button: Provide context</summary>

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads
</details>





<details><summary>:radio_button: Get a green build</summary>

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.
</details><details>


---

<details><summary>Where can I find more information?</summary>

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)
</details>

<details><summary>When can I expect my changes to be merged?</summary>

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*
</details>

File: src/specialExams/data/queryKeys.ts [hunk 1]
```diff
@@ -3,5 +3,8 @@ import { AttemptsParams } from '../types';
 
 export const specialExamsQueryKeys = {
   all: [appId, 'specialExams'] as const,
-  attempts: (courseId: string, params: AttemptsParams) => [...specialExamsQueryKeys.all, 'attempts', courseId, params.page, params.emailOrUsername] as const,
+  byCourse: (courseId: string) => [...specialExamsQueryKeys.all, courseId] as const,
+  attempts: (courseId: string, params: AttemptsParams) => [...specialExamsQueryKeys.byCourse(courseId), 'attempts', params.page, params.emailOrUsername] as const,
+  allowances: (courseId: string, params?: AttemptsParams) => [...specialExamsQueryKeys.byCourse(courseId), 'allowances', params?.page || 1, params?.emailOrUsername || ''] as const,
+  specialExams: (courseId: string) => [...specialExamsQueryKeys.byCourse(courseId), 'specialExams'] as const,
```
Comment (wgu-jesse-stewart) [inline src/specialExams/data/queryKeys.ts]: examType is missing from the query key, so changing from proctored to timed won't trigger a refetch -- the key looks the same to React Query. The useEffect + refetch() in AddAllowanceModal works around this, but the fix is to include examType in specialExams query key and remove the manual refetch

**Review by wgu-jesse-stewart — COMMENTED** [review]
Nice work, just one concern about a possible query key bug

**Review by wgu-jesse-stewart — APPROVED** [review]
