### PR TITLE
fix: Multiple bug fixes

### LINKED ISSUE #161: Fix: Enrollment and Beta Tester actions failing for learner type users
Actions on the Enrollment Management dashboard are failing specifically for users with a **learner role** while functioning correctly for admin accounts. These failures are occurring in the **Sandbox environment** without triggering any error messages or UI feedback.

**Beta Tester Role:** Attempting to assign the Beta Tester role to learner users (e.g., santiagostudent, santiagostudent2) results in no change. However, the action works perfectly when applied to the admin user santiagoSchema.

**Enrollment:** While "Unenroll" works for all users, the "Enroll" action fails for learner accounts. After attempting to enroll a student, the system does not update or add the user to the list. Re-enrolling the admin user santiagoSchema works as expected.

In both cases, the system fails silently for learners with no visual feedback or error messages.

### If want to replicate:
Environment: Sandbox
Affected Users (Learners): santiagostudent, santiagostudent2
Reference User (Admin - Working): santiagoSchema

### LINKED ISSUE #187: Discussion Admin Role Validation
Image

### PR DESCRIPTION
**Pull request by diana-villalvazo-wgu**
## Description
As part of this PR were addressed following fixes:
- Remove duplicated reset attempts button on Grading Tab.
- If a user is inactive and you add it as a beta tester a warning alert should be displayed.
- Add tooltip and don't allow users to edit roles that are not allowed, for example Admins can't remove their own admin role, Discussion Admins can't modify roles different than TA and Discussion roles.

## Supporting information
Closes #187 
Closes #161 

## Screenshots
- Remove duplicated reset attempts button on Grading Tab.
Before
Screenshot 2026-04-28 at 9 25 52 a m

After
Screenshot 2026-04-28 at 9 26 35 a m

- Add tooltip and don't allow users to edit roles that are not allowed, for example Admins can't remove their own admin role, Discussion Admins can't modify roles different than TA and Discussion roles.
Screenshot 2026-04-28 at 9 32 13 a m

Screenshot 2026-04-28 at 9 32 23 a m

Screenshot 2026-04-28 at 9 32 31 a m

## Best Practices Checklist

We're trying to move away from some deprecated patterns in this codebase. Please
check if your PR meets these recommendations before asking for a review:

- [x] Any _new_ files are using TypeScript (`.ts`, `.tsx`).
- [x] Deprecated `propTypes`, `defaultProps`, and `injectIntl` patterns are not used in any new or modified code.
- [x] Tests should use the helpers in `src/testUtils.tsx` (specifically `initializeMocks`)
- [x] Use React Query to load data from REST APIs. See any `apiHooks.ts` in this repo for examples.
- [x] All new i18n messages in `messages.ts` files have a `description` for translators to use.
- [x] Imports avoid using `../`. To import from parent folders, use `@src`, e.g. `import { initializeMocks } from '@src/testUtils';` instead of `from '../../../../testUtils'`

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @diana-villalvazo-wgu!


This repository is currently maintained by `@openedx/committers-frontend-app-instructor-dashboard`.


Once you've gone through the following steps feel free to tag them in a comment and let them know that your changes are ready for engineering review.

<details><summary>:radio_button: Get product approval</summary>

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.
</details>

<details><summary>:radio_button: Provide context</summary>

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads
</details>





<details><summary>:radio_button: Get a green build</summary>

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.
</details><details>


---

<details><summary>Where can I find more information?</summary>

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)
</details>

<details><summary>When can I expect my changes to be merged?</summary>

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*
</details>

File: src/courseTeam/data/apiHook.ts [hunk 1]
```diff
@@ -11,10 +11,10 @@ export const useTeamMembers = (courseId: string, params: CourseTeamMemberQueryPa
   })
 );
 
-export const useRoles = (courseId: string) => (
+export const useRoles = (courseId: string, editableRoles = false) => (
   useQuery({
     queryKey: courseTeamQueryKeys.roles(courseId),
```
Comment (jacobo-dominguez-wgu) [inline src/courseTeam/data/apiHook.ts]: Should `editableRoles` be considered for the query key?

**Review by jacobo-dominguez-wgu — APPROVED** [review]
LGTM!
