### PR TITLE
fix: handle external routes correctly

### LINKED ISSUE #183: External Routing don't work properly
We deployed the repo to master sandbox and find out that the external routing on tabs wasn't working properly, since on this sandbox we have same origin, react router Link from tabs tried to redirect an external route inside instructor dashboard causing a 404, our example is bulk email.

https://github.com/user-attachments/assets/aadac909-dc08-40c3-9179-4efd4a62fc4e

### PR DESCRIPTION
**Pull request by diana-villalvazo-wgu**
## Description
Previously we were having react router link to handle all tabs, but in case is from a different MFE/basepath we should use a regular anchor, so external routes are redirecting correctly.

## Supporting information
Closes #183 

## Best Practices Checklist

We're trying to move away from some deprecated patterns in this codebase. Please
check if your PR meets these recommendations before asking for a review:

- [x] Any _new_ files are using TypeScript (`.ts`, `.tsx`).
- [x] Deprecated `propTypes`, `defaultProps`, and `injectIntl` patterns are not used in any new or modified code.
- [x] Tests should use the helpers in `src/testUtils.tsx` (specifically `initializeMocks`)
- [x] Use React Query to load data from REST APIs. See any `apiHooks.ts` in this repo for examples.
- [x] All new i18n messages in `messages.ts` files have a `description` for translators to use.
- [x] Imports avoid using `../`. To import from parent folders, use `@src`, e.g. `import { initializeMocks } from '@src/testUtils';` instead of `from '../../../../testUtils'`

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @diana-villalvazo-wgu!


This repository is currently maintained by `@openedx/committers-frontend-app-instructor-dashboard`.


Once you've gone through the following steps feel free to tag them in a comment and let them know that your changes are ready for engineering review.

<details><summary>:radio_button: Get product approval</summary>

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.
</details>

<details><summary>:radio_button: Provide context</summary>

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads
</details>





<details><summary>:radio_button: Get a green build</summary>

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.
</details><details>


---

<details><summary>Where can I find more information?</summary>

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)
</details>

<details><summary>When can I expect my changes to be merged?</summary>

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*
</details>

**Review by arbrandes — CHANGES_REQUESTED** [review]
While this does the job, I think it can be much, much simpler.

The current implementation parses URLs against a sentinel origin. The actual input is narrower: tab URLs are either an absolute path (starting with `/`) that this app presumably routes, or a fully qualified URL (starting with a scheme) that points somewhere else. That distinction is exactly what `url.startsWith('/')` captures. The classifier, `instructorDashboardBasePath`, the `courseId` argument, and the `try`/`catch` can all go away:

```tsx
// src/instructorNav/InstructorNav.tsx
sortedTabs.map((tab) => {
  const isInternal = tab.url.startsWith('/');
  return (
    <Nav.Item key={tab.tabId}>
      <Nav.Link
        {...(isInternal
          ? { to: tab.url, as: Link }
          : { href: tab.url }
        )}
        active={tab.tabId === tabId}
        onClick={() => clearAlerts()}
      >
        {tab.title}
      </Nav.Link>
    </Nav.Item>
  );
})
```

Or did I miss some nuance?

**Comment by diana-villalvazo-wgu** [comment]
> While this does the job, I think it can be much, much simpler.
> 
> The current implementation parses URLs against a sentinel origin. The actual input is narrower: tab URLs are either an absolute path (starting with `/`) that this app presumably routes, or a fully qualified URL (starting with a scheme) that points somewhere else. That distinction is exactly what `url.startsWith('/')` captures. The classifier, `instructorDashboardBasePath`, the `courseId` argument, and the `try`/`catch` can all go away:
> 
> ```tsx
> // src/instructorNav/InstructorNav.tsx
> sortedTabs.map((tab) => {
>   const isInternal = tab.url.startsWith('/');
>   return (
>     <Nav.Item key={tab.tabId}>
>       <Nav.Link
>         {...(isInternal
>           ? { to: tab.url, as: Link }
>           : { href: tab.url }
>         )}
>         active={tab.tabId === tabId}
>         onClick={() => clearAlerts()}
>       >
>         {tab.title}
>       </Nav.Link>
>     </Nav.Item>
>   );
> })
> ```
> 
> Or did I miss some nuance?

Yeah this simplifies things, i was just trying to cover cases where we can possibly get full url and still is from instructor-dashboard, but i guess we can keep this one, thx

File: src/instructorNav/InstructorNav.tsx [hunk 1]
```diff
@@ -58,18 +58,23 @@ const InstructorNav = () => {
...
-              </Nav.Item>
-            ))
+            sortedTabs.map((tab) => {
+              const isInternal = tab.url.startsWith('/');
+              return (
+                <Nav.Item key={tab.tabId}>
+                  <Nav.Link
+                    {...(isInternal
+                      ? { to: tab.url, as: Link }
+                      : { href: tab.url, as: 'a' }
```
Comment (arbrandes) [inline src/instructorNav/InstructorNav.tsx]: I believe `as a` is redundant because Paragon already renders Link as an anchor by default.

```suggestion
                      : { href: tab.url }
```

**Review by arbrandes — CHANGES_REQUESTED** [review]
Almost there!  Can we get a test for the case with the external URL, so we cover that new line?

**Review by arbrandes — APPROVED** [review]
