### PR TITLE
fix: change extension due date label

### LINKED ISSUE #163: Changes: Add Individual Due Date Extensions modal
Adjusted the design slightly. These are changes to match patterns in other places where dates are set
Image

1. Change the description text for Define Extension to "Extension Date and time (in UTC):" 
2. Have 00:00 as the default time set

### PR DESCRIPTION
**Pull request by diana-villalvazo-wgu**
## Description
As part of AC Testing, was asked to put as default 11:59 pm and change extension date and time label:

## Supporting information
Closes #163 

## Testing instructions
- Go to date extensions tab
- Click on add date extension

## Other information
Before
Screenshot 2026-04-20 at 9 15 31 a m

After
Screenshot 2026-04-20 at 9 14 21 a m

## Best Practices Checklist

We're trying to move away from some deprecated patterns in this codebase. Please
check if your PR meets these recommendations before asking for a review:

- [x] Any _new_ files are using TypeScript (`.ts`, `.tsx`).
- [x] Deprecated `propTypes`, `defaultProps`, and `injectIntl` patterns are not used in any new or modified code.
- [x] Tests should use the helpers in `src/testUtils.tsx` (specifically `initializeMocks`)
- [x] Use React Query to load data from REST APIs. See any `apiHooks.ts` in this repo for examples.
- [x] All new i18n messages in `messages.ts` files have a `description` for translators to use.
- [x] Imports avoid using `../`. To import from parent folders, use `@src`, e.g. `import { initializeMocks } from '@src/testUtils';` instead of `from '../../../../testUtils'`

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @diana-villalvazo-wgu!


This repository is currently maintained by `@openedx/committers-frontend-app-instructor-dashboard`.


Once you've gone through the following steps feel free to tag them in a comment and let them know that your changes are ready for engineering review.

<details><summary>:radio_button: Get product approval</summary>

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.
</details>

<details><summary>:radio_button: Provide context</summary>

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads
</details>





<details><summary>:radio_button: Get a green build</summary>

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.
</details><details>


---

<details><summary>Where can I find more information?</summary>

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)
</details>

<details><summary>When can I expect my changes to be merged?</summary>

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*
</details>

File: src/dateExtensions/components/AddExtensionModal.tsx [hunk 1]
```diff
@@ -95,7 +94,7 @@ const AddExtensionModal = ({ isOpen, title, onClose, onSubmit }: AddExtensionMod
                 </FormLabel>
                 <div className="d-md-flex w-md-50 align-items-center">
                   <FormControl name="dueDate" type="date" size="md" onChange={onChange} />
-                  <FormControl name="dueTime" type="time" size="md" className="mt-sm-3 mt-md-0" onChange={onChange} />
+                  <FormControl name="dueTime" type="time" size="md" className="mt-sm-3 mt-md-0" defaultValue="23:59" onChange={onChange} />
```
Comment (jesusbalderramawgu) [inline src/dateExtensions/components/AddExtensionModal.tsx]: I see you have the same value in both places, wouldn't be better to have a constant with that value?

**Review by jesusbalderramawgu — APPROVED** [review]
I put a minor comment, but looks good for me

File: src/dateExtensions/components/AddExtensionModal.tsx (hunk 1 above)
Comment (rodmgwgu) [inline src/dateExtensions/components/AddExtensionModal.tsx:97]: Let's make the "23:59" value a constant like "DEFAULT_TIME" so we don't repeat it

**Review by rodmgwgu — APPROVED** [review]
Looks good, thanks!

File: src/dateExtensions/components/AddExtensionModal.tsx (hunk 1 above)
Comment (diana-villalvazo-wgu) [reply src/dateExtensions/components/AddExtensionModal.tsx:97]: i used the initial values as the constant

**Review by wgu-jesse-stewart — APPROVED** [review]
